Add customer_managed_key functionality
claranet/terraform-azurerm-storage-account pull request #16
Opened 2024-06-11 20:58 UTC by blongv

Fixes #15  .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes proposed in this pull request

- Add outputs
- Add customer_managed_key optional block.
- Add infrastructure_encryption_enabled variable.
- Add lifecycle ignore_changes tags for environments where tags are enforced by central policies.

@claranet/fr-azure-reviewers

2024-06-12 09:49 UTC, Shr3ps requested changes

2024-06-12 09:49 UTC, Shr3ps commented on outputs.tf
> +output "storage_account_primary_blob_endpoint" {
This is not needed for your added feature "customer_managed_key" and this endpoint is already available through the `storage_account_properties` output

2024-06-12 09:49 UTC, Shr3ps commented on variables.tf
> +variable "customer_managed_key" {
please use tfdocs to update the README/fix the CI

2024-06-14 09:16 UTC, Shr3ps approved these changes

2024-06-14 09:20 UTC, zfiel commented on r-storage-account.tf
> +    for_each = var.customer_managed_key != null ? ["enabled"] : []
```suggestion
    for_each = var.customer_managed_key[*] 
```

2024-06-14 09:23 UTC, zfiel commented on r-storage-account.tf
> +      managed_hsm_key_id        = try(var.customer_managed_key.managed_hsm_key_id, null)
```suggestion
      key_vault_key_id          = var.customer_managed_key.key_vault_key_id
      managed_hsm_key_id  = var.customer_managed_key.managed_hsm_key_id
```

2024-06-14 09:26 UTC, zfiel approved these changes

2024-06-14 09:26 UTC, merged